# This workflow builds the SDK using Java 11
name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]
jobs:
  # Build and test the SDK
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # All history
    - name: Set SDK version
      run: |
        SDK_VERSION=$(git describe --tags || echo v0.0.0-$(git rev-list --all --count)-g$(git rev-parse --short HEAD))
        SDK_VERSION="${SDK_VERSION:1}"
        echo "::set-env name=SDK_VERSION::$SDK_VERSION"
    - name: Mark build as release
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "::set-env name=SDK_BUILD_ARGS::$(echo '-Prelease=true')"
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test -Pversion=$SDK_VERSION $SDK_BUILD_ARGS
    - name: Run TestProject Agent
      env:
        TP_API_KEY: ${{ secrets.TP_API_KEY }}
      run: |
        envsubst < .github/ci/docker-compose.yml > docker-compose.yml
        docker-compose -f docker-compose.yml up -d
    - name: Wait for Agent to Register
      run: |
        trap 'kill $(jobs -p)' EXIT

        attempt_counter=0
        max_attempts=45

        mkdir -p build/reports/agent
        docker-compose -f docker-compose.yml logs -f | tee build/reports/agent/log.txt&
        until curl -s http://localhost:8585/api/status | jq '.registered' | grep true; do
          if [ ${attempt_counter} -eq ${max_attempts} ]; then
            echo "Agent failed to register. Terminating..."
            exit 1
          fi
          attempt_counter=$(($attempt_counter+1))
          sleep 1
        done
    - name: Run tests
      env:
        TP_DEV_TOKEN: ${{ secrets.TP_DEV_TOKEN }}
        TP_AGENT_URL: http://localhost:8585
      run: |
        trap 'kill $(jobs -p)' EXIT
        export TP_DEBUG_SDK_VERSION=$SDK_VERSION
        docker-compose -f docker-compose.yml logs -f --tail=0 >> build/reports/agent/log.txt&
        ./gradlew test --tests io.testproject.sdk.tests.ci.* -Pversion=$SDK_VERSION $SDK_BUILD_ARGS
    - name: Upload to Maven
      if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/master')
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}        
      run: ./gradlew publish -Pversion=$SDK_VERSION $SDK_BUILD_ARGS
    - name: Publish to Maven
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}        
      run: ./gradlew closeAndReleaseRepository
    - name: Archive reports
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: build/reports
